version: '3.7'

services:

  # Reverse proxy
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    hostname: nginx
    depends_on:
      - auth-service
    ports:
      - 80:80
    networks:
      - app

  # Database product
  # mongo-product:
  #   image: mongo:latest
  #   container_name: mongo-product
  #   hostname: mongo-product
  #   volumes:
  #     - "./mongo-product:/data/db"
  #   ports:
  #     - 27017:27017
  #   restart:
  #     always

  # Database user
  mongo-user:
    image: mongo:focal
    container_name: mongo-user
    hostname: mongo-user
    volumes:
      - "./mongo-user:/data/db"
    ports:
      - 27017:27017
    restart:
      always
    networks:
      - app

  auth-service:
    image: auth-service
    container_name: auth-service
    hostname: auth-service
    build :
      context: ./auth-service
    ports:
      - 3000:3000
    depends_on:
      - mongo-user
    networks:
      - app

networks:
  app:
